import type { Metadata } from 'next';
import './globals.css';
import ReactQueryClientProvider from '@/config/ReactQueryClientProvider';
import { ThemeProvider } from '@/config/MaterialTailwindThemeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReactQueryClientProvider>
        <ThemeProvider value={{ mode: 'dark' }}>
          <body>{children}</body>
        </ThemeProvider>
      </ReactQueryClientProvider>
    </html>
  );
}
